
pipelines:
  default:
    - step:
        image: laurent44/angular-test
        services:
          - docker
        caches:
          - elixir
        script:
          - docker run -d --name=roach1 -p 26257:26257 cockroachdb/cockroach:v1.1.3 start --insecure
          - mix do deps.get, compile
          - mix test    
          - docker stop roach1    
    - step:    
        image: laurent44/phoenix:1.6.0
        caches:
          - node
        script:
          - npm install
          - npm test
definitions:
  caches:
    elixir: deps


        